/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE  from "three";

export default function TerminusTablet(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/terminus_compress.glb')
  useFrame(() => (group.current.rotation.x = group.current.rotation.y += 0.01)) 
  const material = new THREE.MeshStandardMaterial({
    color: 0x545454,
    transparent: true,
    opacity: 0.1,
    wireframe: true,
    roughness: 0
  })
  return (
    <group ref={group} {...props} dispose={null} position={[-3, -3, 0]}>
      <mesh scale={0.045, 0.045, 0.045} geometry={nodes.Fillet7.geometry} material={material} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/terminus_compress.glb')
